# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Main Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build and analyze with Maven
      run: mvn -B --fail-at-end package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=euu-rocks_seed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #- name: Publish Test Report
    #  if: ${{ always() }}
    #  uses: scacap/action-surefire-report@v1
    #  with:
    #    check_name: Seed Report
    #    report_paths: '**/surefire-reports/TEST-*.xml'
    #- name: Install doctl
    #  uses: digitalocean/action-doctl@v2
    #  with:
    #    token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    #- name: REGISTRY LOGIN
    #  run: doctl registry login --expiry-seconds 600
    #- name: DOCKER BUILD
    #  run: docker build -t registry.digitalocean.com/euu/seed .
    #- name: DOCKER PUSH
    #  run: docker push registry.digitalocean.com/euu/seed:latest
    #- name: REGISTRY LOGOUT
   #   run: doctl registry logout
