# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Branch Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version'
        required: true
        default: '0.9.0'
      next_version:
        description: 'Next Snapshot Version'
        required: true
        default: '0.9.1-SNAPSHOT'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Release Version: ${{ github.event.inputs.release_version }}"
          echo "Next Version: ${{ github.event.inputs.next_version }}"
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_RELEASE_TOKEN }}
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Release Version
      run: |
        mvn versions:set -DnewVersion=${{ github.event.inputs.release_version }} -DgenerateBackupPoms=false
        git config user.name "Manager of Releases"
        git config user.email sales@euu.rocks
        git add .
        git commit -m "Release Version ${{ github.event.inputs.release_version }}"
        git tag v${{ github.event.inputs.release_version }}
    - name: Prepare Snapshot
      run: |
        mvn versions:set -DnewVersion=${{ github.event.inputs.next_version }} -DgenerateBackupPoms=false
        git config user.name "Manager of Releases"
        git config user.email sales@euu.rocks
        git add .
        git commit -m "Prepare Snapshot Version ${{ github.event.inputs.next_version }}"
    - name: Push Release and Snapshot
      run: |
        git push
        git push origin v${{ github.event.inputs.release_version }}